// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCq9RzbFHmmCyFvutSaOKv-b16voQDcTc',
    appId: '1:764113985474:web:3877367bbcb7bf74a0405b',
    messagingSenderId: '764113985474',
    projectId: 'apps-junelf',
    authDomain: 'apps-junelf.firebaseapp.com',
    storageBucket: 'apps-junelf.appspot.com',
    measurementId: 'G-6YDR4485EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWwa_w98DzC1ah02dwHL2NVrHQ-jlGKhg',
    appId: '1:764113985474:android:c58eb766db18c565a0405b',
    messagingSenderId: '764113985474',
    projectId: 'apps-junelf',
    storageBucket: 'apps-junelf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHaRmDjkZ8yDqLfO3FeUw4JES4BHQDRqw',
    appId: '1:764113985474:ios:250c0638bf8d8ffda0405b',
    messagingSenderId: '764113985474',
    projectId: 'apps-junelf',
    storageBucket: 'apps-junelf.appspot.com',
    iosClientId: '764113985474-9lt6qbc7ocml4vbdekh4cboutv4biepm.apps.googleusercontent.com',
    iosBundleId: 'com.example.junelfapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHaRmDjkZ8yDqLfO3FeUw4JES4BHQDRqw',
    appId: '1:764113985474:ios:250c0638bf8d8ffda0405b',
    messagingSenderId: '764113985474',
    projectId: 'apps-junelf',
    storageBucket: 'apps-junelf.appspot.com',
    iosClientId: '764113985474-9lt6qbc7ocml4vbdekh4cboutv4biepm.apps.googleusercontent.com',
    iosBundleId: 'com.example.junelfapps',
  );
}
